### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by daqjjang** [scissorstail/KoAlpaca-7B-Quantized#1]
Koalpaca 퀀타제이션 관련하여 올려주셔서 감사합니다.

올려주신 설명에 맞춰 진행하고 있는데 
python export_state_dict_checkpoint.py --base_model "beomi/KoAlpaca"
여기서 자꾸 죽는 현상이 발생합니다.

root@046f59ab7b32:/workspace# python export_state_dict_checkpoint.py --base_model "beomi/KoAlpaca"
Loading checkpoint shards:   0%|                          | 0/3 [00:00<?, ?it/s]죽었음
혹시 관련 현상에 대해서 아시나요?

**Comment by scissorstail** [comment]
RAM이 작아서 그렇습니다. 양자화 한 후에는 4GB 정도를 사용하나 양자화 과정에서는 16GB 이상을 사용하는 것 같습니다.

**Comment by daqjjang** [comment]
아 그렇군요. 빠른 답변 감사합니다!!

**Comment by tae0y** [comment]
저도 같은 증상을 겪었는데, 아래와 같이 max_shard_size 인자를 설정해줬어요.
그리고 호스트 메모리를 모두 사용하기 위해서 파이썬 venv 환경에서 구동했습니다...!

```
tokenizer = LlamaTokenizer.from_pretrained(BASE_MODEL)
base_model = LlamaForCausalLM.from_pretrained(
    BASE_MODEL,
    force_download=True,
    resume_download=False,
    load_in_8bit=False,
    torch_dtype=torch.float16,
    device_map={"": "cpu"},
)

base_model.resize_token_embeddings(len(tokenizer))
assert base_model.get_input_embeddings().weight.size(0) == len(tokenizer)
tokenizer.save_pretrained(output_dir, max_shard_size="200MB")
```
